### ISSUE TITLE
Paths are converted differently in RacketCS

### ISSUE THREAD

**Issue by shhyou** [racket/pconvert-lib#9]
In Racket BC, paths are left as-is while in Racket CS paths are turned into `'path` plus dots.

EDIT: in this case, it is unclear what ought to be the correct behavior (if there's any). There while Racket BC and Racket CS disagree, this is not really a bug.

Program:
```
#lang racket/base
(require mzlib/pconvert)
(print-convert (build-path "dir"))
```

In Racket BC v7.9:
```
#<path:dir>
```

In Racket CS v7.9.0.22:
```
(path ...)
```

**Comment by mflatt** [comment]
This is a Racket CS bug where `object-name` reports `'path` for a path. I'll push a repair there.

**Comment by shhyou** [comment]
Interesting. Thanks for the fix!
